config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :books
  resources :loan_transactions
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

	has_many :load_transaction_details

	validates :title, presence: true
	validates :description, presence: true
	validates :category, presence: true

	enum category: {komik: 1, novel: 2, biografi: 3}
	scope :filter_search, -> (search = nil) {where("title like ? OR description like ?", "%#{search}%", "%#{search}%") if search.present?}

end

app/models/loan_transaction.rb
class LoanTransaction < ApplicationRecord

	belongs_to :user
	has_many :loan_transaction_details
	accepts_nested_attributes_for :loan_transaction_details

	scope :filter_search, -> (search = nil) {joins(:user, {loan_transaction_details: :book}).where("users.name like ? OR books.title like ?", "%#{search}%", "%#{search}%") if search.present?}
end

app/models/loan_transaction_detail.rb
class LoanTransactionDetail < ApplicationRecord

	belongs_to :loan_transaction
	belongs_to :book
end

app/models/user.rb
class User < ApplicationRecord
	has_many :loan_transactions
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
	before_action :define_book, only: [:edit, :update]

	def index
		@books = Book.filter_search(params[:search]).order(created_at: :desc)
	end

	def new
		@book = Book.new
	end

	def create
		@book = Book.new(params_book)
		if @book.save
			redirect_to books_path
		else
			redirect_back new_book_path
		end
	end

	def edit
		
	end

	def update
		if @book.update(params_book)
			redirect_to books_path
		else
			redirect_back new_book_path
		end
	end

	private

	def params_book
		params.fetch(:book, {}).permit(:title, :description, :category)
	end

	def define_book
		@book = Book.find(params[:id])
	end
end

app/controllers/loan_transactions_controller.rb
class LoanTransactionsController < ApplicationController
	before_action :define_loan_transaction, only: [:show]

	def index
		@loan_transactions = LoanTransaction.filter_search(params[:search]).order(created_at: :desc).uniq
	end

	def new
		@loan_transaction = LoanTransaction.new
		@user = User.all
		@book = Book.all
	end

	def create
		@loan_transaction = LoanTransaction.new(params_loan_transaction)
		if @loan_transaction.save
			redirect_to loan_transactions_path
		else
			redirect_back new_loan_transaction_path
		end
	end

	def show
		
	end

	private

	def params_loan_transaction
		params.fetch(:loan_transaction, {}).permit(:due_date, :user_id, loan_transaction_details_attributes: [:book_id])
	end

	def define_loan_transaction
		@loan_transaction = LoanTransaction.find(params[:id])
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/loan_transactions_helper.rb
module LoanTransactionsHelper
end

app/views/books/edit.html.erb
<section class="content-header">
  <h1>
    Book
    <small>Form</small>
  </h1>
</section>

<section class="content">
  <div class="row">

    <div class="col-md-12">
      <div class="card">
        <div class="card-header">
          <h3 class="card-title">Edit Book</h3>
        </div>
        <div class="card-content">
          <div class="card-body">
            <%= render "books/shared/form", url: book_path, book: @book %>
          </div>
        </div>
          </form>
        </div>

      </div>
    </div>
  </div>
</section>

app/views/books/index.html.erb
<section class="content">
	<div class="row">
		<div class="card">
			<div class="card-content">
				<div class="row">
					<div class="col-md-3">
						<a href="<%= new_book_path %>" class="btn btn-sm btn-success mt-2">New</a>
					</div>
					<div class="col-md-9">
						<%= form_tag(books_path, method: 'get') do %>
	            <div class="input-group mt-2">
               	<%= text_field_tag :search, params[:search], :class => "form-control", placeholder: "Search", autocomplete: "off" %>
	            </div>
          	<% end %>
					</div>
				</div>
			</div>
			<div class="card-body table-responsive">
				<table class="table table-hover">
					<thead>
						<tr>
							<th>Id</th>
							<th>Title</th>
							<th>Description</th>
							<th>Category</th>
							<th>Created At</th>
							<th>Action</th>
						</tr>
					</thead>
					<tbody>
						<% @books.each do |book| %>
							<tr>
								<td><%= book.id %></td>
								<td><%= book.title %></td>
								<td><%= book.description %></td>
								<td><%= book.category %></td>
								<td><%= book.created_at %></td>
								<td>
									<a href="<%= edit_book_path(book) %>" class="btn btn-sm btn-success">Edit</a>
								</td>
							</tr>
						<% end %>
					</tbody>
				</table>
			</div>
		</div>
	</div>
</section>

app/views/books/new.html.erb
<section class="content-header">
  <h1>
    Book
    <small>Form</small>
  </h1>
</section>

<section class="content">
  <div class="row">

    <div class="col-md-12">
      <div class="card">
        <div class="card-header">
          <h3 class="card-title">Create New Book</h3>
        </div>
        <div class="card-content">
          <div class="card-body">
            <%= render "books/shared/form", url: books_path, book: @book %>
          </div>
        </div>
          </form>
        </div>

      </div>
    </div>
  </div>
</section>

app/views/books/shared/_form.html.erb
<%= form_with(model: @book, url: url, class: "form form-vertical", remote: true) do |form| %>
  <div class="form-body">
    <% if @book.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h2>
        <ul>
          <% @book.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <div class="row">
      <div class="col-12">
        <div class="form-group">
          <%= form.label :title %>
          <%= form.text_field :title, class: "form-control", required: true %>
        </div>

        <div class="form-group">
          <%= form.label :description %>
          <%= form.text_area :description, class: "form-control", required: true %>
        </div>

        <div class="form-group">
          <%= form.label :category %>
          <%= form.collection_select :category, ['komik', 'novel', 'biografi'], :to_s, :to_s, {prompt: 'Pilih Category'}, class: "form-control", required: true%>
        </div>
      </div>
      <div class="col-12 d-flex justify-content-end">
       <%= form.submit "Save", class: "btn btn-primary mt-3 mb-1" %>
       <%= link_to 'Back', books_path, class: "btn btn-secondary mt-3 mb-1" %>
      </div>
    </div>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LibraryApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="wrapper" id="wrapper_page">
      <input type="hidden" id="admin_token">
      <%= render "layouts/shared/header"%>

      <div class="content-wrapper container">
        <%= yield %>
      </div>
    </div>
    <%#= yield %>
  </body>
</html>

app/views/layouts/shared/_header.html.erb
<header class="main-header container">
	<br>
  <a href="<%= books_path %>" class="sidebar-toggle">
    <span class="sr-only">Books</span>
  </a>
 	<br>
  <a href="<%= loan_transactions_path %>" class="sidebar-toggle">
    <span class="sr-only">Transaction</span>
  </a>
</header>

app/views/loan_transactions/edit.html.erb
<section class="content-header">
  <h1>
    Transaction
    <small>Form</small>
  </h1>
</section>

<section class="content">
  <div class="row">

    <div class="col-md-12">
      <div class="card">
        <div class="card-header">
          <h3 class="card-title">Edit Transaction</h3>
        </div>
        <div class="card-content">
          <div class="card-body">
            <%= render "loan_transactions/shared/form", url: loan_transaction_path, loan_transaction: @loan_transaction %>
          </div>
        </div>
          </form>
        </div>

      </div>
    </div>
  </div>
</section>

app/views/loan_transactions/index.html.erb
<section class="content">
	<div class="row">
		<div class="card">
			<div class="card-content">
				<div class="row">
					<div class="col-md-3">
						<a href="<%= new_loan_transaction_path %>" class="btn btn-sm btn-success mt-2">New</a>
					</div>
					<div class="col-md-9">
						<%= form_tag(loan_transactions_path, method: 'get') do %>
	            <div class="input-group mt-2">
               	<%= text_field_tag :search, params[:search], :class => "form-control", placeholder: "Search", autocomplete: "off" %>
	            </div>
          	<% end %>
					</div>
				</div>
			</div>
			<div class="card-body table-responsive">
				<table class="table table-hover">
					<thead>
						<tr>
							<th>Id</th>
							<th>Due Date</th>
							<th>Return</th>
							<th>User</th>
							<th>Created At</th>
							<th>Action</th>
						</tr>
					</thead>
					<tbody>
						<% @loan_transactions.each do |loan_transaction| %>
							<tr>
								<td><%= loan_transaction.id %></td>
								<td><%= loan_transaction.due_date.strftime("%d-%m-%Y") %></td>
								<td><%= loan_transaction.is_return %></td>
								<td><%= loan_transaction.try(:user).try(:name) %></td>
								<td><%= loan_transaction.created_at %></td>
								<td>
									<a href="<%= loan_transaction_path(loan_transaction) %>" class="btn btn-sm btn-success">Show</a>
								</td>
							</tr>
						<% end %>
					</tbody>
				</table>
			</div>
		</div>
	</div>
</section>

app/views/loan_transactions/new.html.erb
<section class="content-header">
  <h1>
    Transaction
    <small>Form</small>
  </h1>
</section>

<section class="content">
  <div class="row">

    <div class="col-md-12">
      <div class="card">
        <div class="card-header">
          <h3 class="card-title">Create New Transaction</h3>
        </div>
        <div class="card-content">
          <div class="card-body">
            <%= render "loan_transactions/shared/form", url: loan_transactions_path, loan_transaction: @loan_transaction %>
          </div>
        </div>
          </form>
        </div>

      </div>
    </div>
  </div>
</section>

app/views/loan_transactions/shared/_form.html.erb
<%= form_with(model: @loan_transaction, url: url, class: "form form-vertical", remote: true) do |form| %>
  <div class="form-body">
    <% if @loan_transaction.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@loan_transaction.errors.count, "error") %> prohibited this loan_transaction from being saved:</h2>
        <ul>
          <% @loan_transaction.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <div class="row">
      <div class="col-12">
        <div class="form-group">
          <%= form.label :due_date %>
          <%= form.date_field :due_date, class: "form-control", required: true %>
        </div>

        <div class="form-group">
          <%= form.label :user %>
          <%= form.collection_select :user_id, @user, :id, :name, {}, class: "form-control", required: true %>
        </div>

        <div class="form-group">
          <%= form.label :book %>
          <a href="#" class="btn btn-sm btn-primary" data-bs-toggle="modal" data-bs-target="#book">Select Book</a>
          <div id="list_book">
            
          </div>
        </div>
      </div>
      <div class="col-12 d-flex justify-content-end">
       <%= form.submit "Save", class: "btn btn-primary mt-3 mb-1" %>
       <%= link_to 'Back', books_path, class: "btn btn-secondary mt-3 mb-1" %>
      </div>
    </div>
  </div>
<% end %>

<div class="modal fade" id="book" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title" id="myModalLabel">LIST BOOK</h4>
      </div>
      <div class="modal-body">
        <div class="box-body table-responsive">
          <table class="table table-hover">
            <thead style="background-color: darkgray">
              <tr>
                <th>ID</th>
                <th>Title</th>
                <th>Description</th>
                <th>Category</th>
                <th>Action</th>
              </tr>
            </thead>
            <tbody id="listproductsinpromo">
              <% @book.each do |book| %>
                <tr>
                  <td><%= book.id %></td>
                  <td><%= book.title %></td>
                  <td><%= book.description %></td>
                  <td><%= book.category %></td>
                  <td>
                    <a href="#" class="btn btn-sm btn-success" onclick="addBook(<%= book.id %>, '<%= book.title %>')">Add</a>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-light-secondary"
            data-bs-dismiss="modal">
            <span class="d-none d-sm-block">Tutup</span>
        </button>
      </div>
    </div>
  </div>
</div>

<script>
  function addBook(id, title) {
    document.getElementById("list_book").innerHTML += "<input type='hidden' class='form-control' name='loan_transaction[loan_transaction_details_attributes][][book_id]' value='" + id + "'><input type='text' class='form-control' name='' value='" + title + "' disabled>"
  }
</script>

app/views/loan_transactions/show.html.erb
<section class="content">
	<div class="row">
		<div class="card">
			<div class="card-body table-responsive">
				<table class="table table-hover">
					<thead>
						<tr>
							<th>Id</th>
							<th>Book</th>
						</tr>
					</thead>
					<tbody>
						<% @loan_transaction.loan_transaction_details.each do |detail| %>
							<tr>
								<td><%= detail.id %></td>
								<td><%= detail.book.title %></td>
							</tr>
						<% end %>
					</tbody>
				</table>
			</div>
		</div>
	</div>
</section>